# Generated by Django 3.0.4 on 2020-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chek_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(verbose_name='Time request')),
                ('call', models.CharField(max_length=10)),
            ],
        ),
    ]
