# Generated by Django 3.0.4 on 2020-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telnet_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(verbose_name='Time-register')),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
