# Generated by Django 3.0.4 on 2020-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telnet_server', '0002_register_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Time_new')),
                ('version', models.CharField(max_length=10)),
                ('github_path', models.CharField(max_length=255)),
            ],
        ),
    ]
