# Generated by Django 3.0.4 on 2020-03-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telnet_server', '0004_auto_20200326_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('footer', models.TextField(max_length=1000)),
            ],
        ),
    ]
