# Generated by Django 3.0.4 on 2020-03-27 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telnet_server', '0005_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='h1',
            field=models.CharField(default=datetime.datetime(2020, 3, 27, 11, 49, 46, 22403, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time edit'),
            preserve_default=False,
        ),
    ]
